server:
  port: 8082
  servlet:
    context-path: /xk

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xk?serverTimezone=Asia/Shanghai&useunicode=true&characterEncoding=utf8&useSSL=false
    username: root
#    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 60000
      validation-timeout: 3000
      login-timeout: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
